#!/usr/bin/env bash
# Verify and unpack a GPU training client archive generated by create_client_kit.sh.
set -euo pipefail

ARCHIVE=""
CHECKSUM=""
TARGET="${UENV_TRAINING_CLIENT_DIR:-$HOME/uenv-training-client}"

fail() {
  echo "错误：$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
校验并解压 UEnv GPU 训练客户端包

用法：
  install-training-client.sh --archive FILE [--checksum FILE] [--target DIR]

默认 checksum 为 FILE.sha256，目标目录为 $HOME/uenv-training-client。
目标目录必须不存在；脚本会先校验 SHA-256 和压缩包路径，再原子放入目标目录。
EOF
}

while (($#)); do
  case "$1" in
    --archive) ARCHIVE="${2:-}"; shift 2 ;;
    --checksum) CHECKSUM="${2:-}"; shift 2 ;;
    --target) TARGET="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) fail "未知参数：$1" ;;
  esac
done

[[ -n "$ARCHIVE" && -f "$ARCHIVE" ]] || fail "必须通过 --archive 提供客户端 tar.gz"
CHECKSUM="${CHECKSUM:-$ARCHIVE.sha256}"
[[ -f "$CHECKSUM" ]] || fail "找不到校验文件：$CHECKSUM"
[[ ! -e "$TARGET" ]] || fail "目标目录已存在：$TARGET"

expected="$(awk 'NR == 1 {print $1}' "$CHECKSUM")"
[[ "$expected" =~ ^[0-9a-fA-F]{64}$ ]] || fail "校验文件格式错误：$CHECKSUM"
actual="$(sha256sum "$ARCHIVE" | awk '{print $1}')"
[[ "$actual" == "$expected" ]] || fail "SHA-256 不匹配，拒绝解压"

python3 - "$ARCHIVE" <<'PY'
import sys
import tarfile
from pathlib import PurePosixPath

with tarfile.open(sys.argv[1], "r:gz") as archive:
    for member in archive.getmembers():
        path = PurePosixPath(member.name)
        if path.is_absolute() or ".." in path.parts or not path.parts:
            raise SystemExit(f"unsafe archive path: {member.name}")
        if path.parts[0] != "uenv-training-client":
            raise SystemExit(f"unexpected archive root: {member.name}")
        if member.issym() or member.islnk():
            raise SystemExit(f"archive links are not allowed: {member.name}")
PY

parent="$(dirname "$TARGET")"
mkdir -p "$parent"
parent="$(cd "$parent" && pwd)"
target_name="$(basename "$TARGET")"
TARGET="$parent/$target_name"
temporary="$(mktemp -d -p "$parent" .uenv-training-client.XXXXXXXX)"
cleanup() {
  if [[ -n "${temporary:-}" && -d "$temporary" ]]; then
    find "$temporary" -depth -delete
  fi
  return 0
}
trap cleanup EXIT HUP INT TERM
tar -xzf "$ARCHIVE" -C "$temporary"
mv "$temporary/uenv-training-client" "$TARGET"
find "$temporary" -depth -delete
temporary=""

echo "训练客户端已安装：$TARGET"
echo "下一步：bash '$TARGET/examples/training/train_verl.sh' run-task --help"
