# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from uenv.v1 import agent_pb2 as uenv_dot_v1_dot_agent__pb2


class AgentControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/uenv.v1.AgentControlService/RegisterAgent',
                request_serializer=uenv_dot_v1_dot_agent__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=uenv_dot_v1_dot_agent__pb2.RegisterAgentResponse.FromString)
        self.AgentHeartbeat = channel.unary_unary(
                '/uenv.v1.AgentControlService/AgentHeartbeat',
                request_serializer=uenv_dot_v1_dot_agent__pb2.AgentHeartbeatRequest.SerializeToString,
                response_deserializer=uenv_dot_v1_dot_agent__pb2.AgentHeartbeatResponse.FromString)
        self.PollAgentJob = channel.unary_unary(
                '/uenv.v1.AgentControlService/PollAgentJob',
                request_serializer=uenv_dot_v1_dot_agent__pb2.PollAgentJobRequest.SerializeToString,
                response_deserializer=uenv_dot_v1_dot_agent__pb2.PollAgentJobResponse.FromString)
        self.CompleteAgentJob = channel.unary_unary(
                '/uenv.v1.AgentControlService/CompleteAgentJob',
                request_serializer=uenv_dot_v1_dot_agent__pb2.AgentJobCompleteRequest.SerializeToString,
                response_deserializer=uenv_dot_v1_dot_agent__pb2.AgentJobCompleteResponse.FromString)


class AgentControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollAgentJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteAgentJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=uenv_dot_v1_dot_agent__pb2.RegisterAgentRequest.FromString,
                    response_serializer=uenv_dot_v1_dot_agent__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'AgentHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.AgentHeartbeat,
                    request_deserializer=uenv_dot_v1_dot_agent__pb2.AgentHeartbeatRequest.FromString,
                    response_serializer=uenv_dot_v1_dot_agent__pb2.AgentHeartbeatResponse.SerializeToString,
            ),
            'PollAgentJob': grpc.unary_unary_rpc_method_handler(
                    servicer.PollAgentJob,
                    request_deserializer=uenv_dot_v1_dot_agent__pb2.PollAgentJobRequest.FromString,
                    response_serializer=uenv_dot_v1_dot_agent__pb2.PollAgentJobResponse.SerializeToString,
            ),
            'CompleteAgentJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteAgentJob,
                    request_deserializer=uenv_dot_v1_dot_agent__pb2.AgentJobCompleteRequest.FromString,
                    response_serializer=uenv_dot_v1_dot_agent__pb2.AgentJobCompleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uenv.v1.AgentControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uenv.v1.AgentControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uenv.v1.AgentControlService/RegisterAgent',
            uenv_dot_v1_dot_agent__pb2.RegisterAgentRequest.SerializeToString,
            uenv_dot_v1_dot_agent__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def AgentHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uenv.v1.AgentControlService/AgentHeartbeat',
            uenv_dot_v1_dot_agent__pb2.AgentHeartbeatRequest.SerializeToString,
            uenv_dot_v1_dot_agent__pb2.AgentHeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def PollAgentJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uenv.v1.AgentControlService/PollAgentJob',
            uenv_dot_v1_dot_agent__pb2.PollAgentJobRequest.SerializeToString,
            uenv_dot_v1_dot_agent__pb2.PollAgentJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def CompleteAgentJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uenv.v1.AgentControlService/CompleteAgentJob',
            uenv_dot_v1_dot_agent__pb2.AgentJobCompleteRequest.SerializeToString,
            uenv_dot_v1_dot_agent__pb2.AgentJobCompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)
