apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - worker-config.yaml
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
  - worker-service.yaml
  - worker-deployment.yaml
