apiVersion: v1
kind: Service
metadata:
  name: uenv-worker-control
  labels:
    app.kubernetes.io/part-of: uenv
    uenv.io/component: worker
spec:
  selector:
    app.kubernetes.io/part-of: uenv
    uenv.io/component: worker
  ports:
    - name: control
      port: 28888
      targetPort: 28888
    - name: gateway
      port: 28097
      targetPort: 28097
    - name: metrics
      port: 19090
      targetPort: 19090
