/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServerRouteImport } from './routes/server'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerWorkerRouteImport } from './routes/server_.worker'

const ServerRoute = ServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerWorkerRoute = ServerWorkerRouteImport.update({
  id: '/server_/worker',
  path: '/server/worker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/server': typeof ServerRoute
  '/server/worker': typeof ServerWorkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/server': typeof ServerRoute
  '/server/worker': typeof ServerWorkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/server': typeof ServerRoute
  '/server_/worker': typeof ServerWorkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/server' | '/server/worker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/server' | '/server/worker'
  id: '__root__' | '/' | '/server' | '/server_/worker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServerRoute: typeof ServerRoute
  ServerWorkerRoute: typeof ServerWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/server': {
      id: '/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof ServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server_/worker': {
      id: '/server_/worker'
      path: '/server/worker'
      fullPath: '/server/worker'
      preLoaderRoute: typeof ServerWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServerRoute: ServerRoute,
  ServerWorkerRoute: ServerWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
