/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as ServerRouteImport } from './routes/server'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerWorkerRouteImport } from './routes/server_.worker'
import { Route as ServerAgentsRouteImport } from './routes/server_.agents'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRoute = ServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerWorkerRoute = ServerWorkerRouteImport.update({
  id: '/server_/worker',
  path: '/server/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerAgentsRoute = ServerAgentsRouteImport.update({
  id: '/server_/agents',
  path: '/server/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ops': typeof OpsRoute
  '/server': typeof ServerRoute
  '/system': typeof SystemRoute
  '/server/agents': typeof ServerAgentsRoute
  '/server/worker': typeof ServerWorkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ops': typeof OpsRoute
  '/server': typeof ServerRoute
  '/system': typeof SystemRoute
  '/server/agents': typeof ServerAgentsRoute
  '/server/worker': typeof ServerWorkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ops': typeof OpsRoute
  '/server': typeof ServerRoute
  '/system': typeof SystemRoute
  '/server_/agents': typeof ServerAgentsRoute
  '/server_/worker': typeof ServerWorkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ops'
    | '/server'
    | '/system'
    | '/server/agents'
    | '/server/worker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ops' | '/server' | '/system' | '/server/agents' | '/server/worker'
  id:
    | '__root__'
    | '/'
    | '/ops'
    | '/server'
    | '/system'
    | '/server_/agents'
    | '/server_/worker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpsRoute: typeof OpsRoute
  ServerRoute: typeof ServerRoute
  SystemRoute: typeof SystemRoute
  ServerAgentsRoute: typeof ServerAgentsRoute
  ServerWorkerRoute: typeof ServerWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server': {
      id: '/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof ServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server_/worker': {
      id: '/server_/worker'
      path: '/server/worker'
      fullPath: '/server/worker'
      preLoaderRoute: typeof ServerWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server_/agents': {
      id: '/server_/agents'
      path: '/server/agents'
      fullPath: '/server/agents'
      preLoaderRoute: typeof ServerAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpsRoute: OpsRoute,
  ServerRoute: ServerRoute,
  SystemRoute: SystemRoute,
  ServerAgentsRoute: ServerAgentsRoute,
  ServerWorkerRoute: ServerWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
